name: 'quality-assurance'
run-name: 'Quality Assurance for ${{ github.ref_name }}'
on:
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    container: swift
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: swift-test
      run: swift test

  lint:
    name: 'Lint source'
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Action for SwiftLint (Only files changed in the PR)
      uses: norio-nomura/action-swiftlint@3.2.1
      env:
        DIFF_BASE: ${{ github.base_ref }}